### ISSUE TITLE
Error loading plugin homebridge-isy-maker

### ISSUE THREAD

**Issue by gagy2** [suderman/homebridge-isy-maker#1]
Hi, I'm not sure if this is where I have write if I have problem with the plugin. 
I've been using the homebridge-isy plugin for the past few months and loving it, but your plugin seems to add what I was missing from it so it would be great to have them both! 

I'm trying to run this on a raspberry pi 3. Homebridge is starting fine with only homebridge-isy, but as soon as I install the home bridge-isy-maker plugin, home bridge fails with the following error: (see attached). 

Any idea what I could check to troubleshoot?
Thanks and please let me know if I should be submitting the request somewhere else!

Keep up the good work and can't wait to see it running in my home ;)

![homebridge-isy-maker](https://cloud.githubusercontent.com/assets/23300694/20042597/0a288a3e-a44b-11e6-9f89-b892cdd150a8.png)

**Comment by suderman** [comment]
Hmm, it's hard to tell since that doesn't give me a line number in the plugin. The last line does mention Array.forEach, though... maybe it's your version of node running? For comparison, I'm running node 6.2.1.

**Comment by gagy2** [comment]
I agree, line numbers would have helped... 
Thanks for the tip, I'm running on a Raspberry Pi 3 and Node -v returns v4.3.2 that might be the issue. I'll try to see if I can update to something closer to 6.2.1 and let you know if it did the trick.
Thanks again!

**Comment by gagy2** [comment]
It's now working! Thanks for your recommendation, I'm now running node 6.9.1 and no more errors with homebridge-isy-maker. 

If it can help anyone, I followed the following (after rebuilding my Pi from the latest image.
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-P

This is the part for node:
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

Thanks again for your quick reply. Now time for testing ;)

**Comment by suderman** [comment]
OK, great! Thanks for clarifying the node version requirement. Now that I think about it, the JavaScript syntax I wrote uses a lot of the newer ES6 features, so it makes sense older versions of node would choke.
