### ISSUE TITLE
How to run it inside the ISY994i box?

### ISSUE THREAD

**Issue by peterlo2000** [suderman/homebridge-isy-maker#4]
It works fine if I run homebridge on my computer, but unfortunately, my computer will not always open 24hrs every day, therefore, I am wondering is there a way to have it install into the ISY994i machine?

According to the Universal Devices wiki, we can only telnet directly to the ISY994i machine, but the ISY Shell commands are very limited, so I am not sure will it possible to have homebridge run inside the machine instead of in the computer.  Thanks.

**Comment by suderman** [comment]
I'm afraid not. Homebridge requires nodejs, and the ISY cannot run nodejs (or anything else really).

I installed Homebridge on a Raspberry Pi. I was already using this Rapsberry Pi to run Universal Device's [Polyglot server](https://forum.universal-devices.com/forum/111-polyglot/) (which communicates with [ISY 5.0](https://forum.universal-devices.com/forum/108-50/)), so it was a natural fit to include Homebridge on that device too.

**Comment by peterlo2000** [comment]
Thanks for the information, and I will start to look into the Rapsberry Pi configuration.

Any suggestion of what we need to have/prepare in order to have HomeBridge to run properly in Rapsberry Pi.  Thanks.

**Comment by suderman** [comment]
When I set up my Raspberry Pi 3, I followed this tutorial:

https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

I'm sure I'm out of date now, but I currently run Raspbian 8, node 6.11.3, and homebridge 0.4.28.
